# EINKAUFSLISTE-GO-GIN COMPOSE
# Deploys einkaufsliste-vue as frontend,
#   einkaufsliste-go-gin as backend,
#   postgresql as database
# Creates internal network int-einkaufsliste-net
# db:
#   data: VOLUME einkaufsliste-db-volume

version: '3.8'

services:
  # postgresql database
  db:
    container_name: einkaufsliste-db
    image: postgres:latest
    restart: unless-stopped
    hostname: einkaufsliste-db
    environment:
      # CHANGE VALUES HERE
      - POSTGRES_PASSWORD=asdasd
      - POSTGRES_USER=test
      - POSTGRES_DB=shopping
    volumes:
      - einkaufsliste-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      int-einkaufsliste-net:
        ipv4_address: 172.26.1.3

  # einkaufsliste-vue frontend service
  # https://github.com/c-jaenicke/einkaufsliste-vue
  frontend:
    container_name: einkaufsliste-frontend
    image: einkaufsliste-vue:latest
    restart: unless-stopped
    #expose:
    #  - 80
    ports:
      - 4220:80
    networks:
      int-einkaufsliste-net:
      default:
    # labels:

  # einkaufsliste-go-gin api service
  # https://github.com/c-jaenicke/einkaufsliste-go-gin
  api:
    depends_on:
      - db
    container_name: einkaufsliste-api
    hostname: einkaufsliste-api
    image: einkaufsliste-rest:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    #expose:
    #  - 8080
    environment:
      # CHANGE VALUES HERE
      - POSTGRES_URL=postgresql://test:asdasd@172.26.1.3:5432/shopping
    networks:
      int-einkaufsliste-net:
        ipv4_address: 172.26.1.4
      default:

volumes:
  # volume for postgresql database
  einkaufsliste-db-volume:

networks:
  # bridge network to host machine
  default:
    driver: bridge
  # internal network for communication between frontend to api, and api to database
  int-einkaufsliste-net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.26.1.0/28"