version: '3.8'


services:
  # postgresql database
  db:
    container_name: einkaufsliste-db
    image: postgres:latest
    restart: unless-stopped
    hostname: einkaufsliste-db
    environment:
      - POSTGRES_PASSWORD=asdasd
      - POSTGRES_USER=test
      - POSTGRES_DB=shopping
    volumes:
      - einkaufsliste-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      int-einkaufsliste-net:
        ipv4_address: 172.26.1.3

  frontend:
    container_name: einkaufsliste-frontend
    image: einkaufsliste-vue:latest
    restart: unless-stopped
    #expose:
    #  - 80
    ports:
      - 4220:80
    networks:
      int-einkaufsliste-net:
      default:

  api:
    depends_on:
      - db
    container_name: einkaufsliste-api
    hostname: einkaufsliste-api
    image: einkaufsliste-rest:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    #expose:
    #  - 8080
    environment:
      #- POSTGRES_URL=postgresql://test:asdasd@172.21.0.2:5432/shopping
      - POSTGRES_URL=postgresql://test:asdasd@172.26.1.3:5432/shopping
    networks:
      int-einkaufsliste-net:
        ipv4_address: 172.26.1.4
      default:
      shopping-list-go-gin_default:



volumes:
  einkaufsliste-db-volume:

networks:
  default:
    driver: bridge
  int-einkaufsliste-net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.26.1.0/28"
#    driver_opts:
#      --subnet: "172.26.1.0/28"
  shopping-list-go-gin_default:
    external: true
    name: shopping-list-go-gin_default
