# EINKAUFSLISTE-GO-GIN COMPOSE
version: "3.9"

services:
  # postgres db for saving items
  db:
    container_name: einkaufsliste-db
    image: postgres:latest
    restart: unless-stopped
    hostname: einkaufsliste-db
    environment:
      # CHANGE VALUES HERE
      - POSTGRES_PASSWORD=asdasd
      - POSTGRES_USER=test
      - POSTGRES_DB=shopping
    volumes:
      - einkaufsliste-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      int-einkaufsliste-net:
        ipv4_address: 172.26.1.3

  # einkaufsliste-vue frontend service
  # https://github.com/c-jaenicke/einkaufsliste-vue
  frontend:
    container_name: einkaufsliste-frontend
    image: einkaufsliste-vue:latest
    restart: unless-stopped
    #expose:
    #  - 80
    ports:
      - 4220:80
    networks:
      int-einkaufsliste-net:
        ipv4_address: 172.26.1.2
      default:

  # einkaufsliste-go-gin api service
  # https://github.com/c-jaenicke/einkaufsliste-go-gin
  api:
    depends_on:
      - db
    container_name: einkaufsliste-api
    hostname: einkaufsliste-api
    image: einkaufsliste-rest:latest
    restart: unless-stopped
    expose:
      - 8080
    environment:
      - POSTGRES_URL=postgresql://test:asdasd@172.26.1.3:5432/shopping
      - "ALLOWED_ORIGINS="
    networks:
      int-einkaufsliste-net:
        ipv4_address: 172.26.1.4
      default:

volumes:
  einkaufsliste-db-volume:

networks:
  default:
    driver: bridge
  #  external: true
  #  name: int-docker-net
  int-einkaufsliste-net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.26.1.0/28"