# docker compose for local testing and simple deploy
version: "3.9"

services:
  db:
    container_name: einkaufsliste-db
    hostname: einkaufsliste-db
    image: postgres:15
    restart: unless-stopped
    environment:
      # change values here!
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    volumes:
      - einkaufsliste-db-volume:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d db -U user" ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    container_name: einkaufsliste-frontend
    hostname: einkaufsliste-frontend
    image: einkaufsliste-svelte:latest
    restart: unless-stopped
    environment:
      - "ORIGIN=http://localhost:3000"
    ports:
      - 3000:3000
    expose:
      - 3000

  backend:
    container_name: einkaufsliste-api
    hostname: einkaufsliste-api
    image: einkaufsliste-rest:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      # make sure to change values here! need to be the same as above!
      - DSS=host=einkaufsliste-db port=5432 user=user dbname=db password=pass sslmode=disable
      # switch gin mode [debug|test|release]
      - GIN_MODE=release
      # set allowed origins for cors
      - ALLOWED_ORIGINS=http://localhost:3000
    expose:
      - 8080
    depends_on:
      db:
        condition: service_healthy

volumes:
  einkaufsliste-db-volume:

networks:
  default:
    driver: bridge
